name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-action: # make sure build/ci work properly
    name: Run action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
            
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build 

      - name: Test Action
        uses: ./
